"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useSession } from "next-auth/react";
import { motion, AnimatePresence } from "framer-motion";
import SideRays from "../components/SideRays";
import LineWaves from "../components/LineWaves";
import DecryptedText from "../components/DecryptedText";
import DotField from "../components/DotField";
import TruthsSection from "../components/TruthsSection";

export default function Home() {
  const [state, setState] = useState<"void" | "gatekeeper" | "protocol">("void");
  const router = useRouter();
  const { data: session, status } = useSession();

  const handleEnter = () => {
    if (status === "authenticated") {
      router.push("/campaign");
    } else {
      setState("gatekeeper");
    }
  };

  return (
    <main className={`min-h-screen w-full bg-black font-sans selection:bg-red-900 selection:text-white ${state === "protocol" ? "" : "flex flex-col items-center justify-center overflow-hidden"}`}>
      <AnimatePresence mode="wait">
        {state === "void" && (
          <motion.div
            key="void"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.8, ease: "easeInOut" }}
            className="flex items-center justify-center w-full h-full absolute inset-0"
          >
            <div className="absolute inset-0 z-0">
              <LineWaves 
                speed={0.25}
                innerLineCount={30}
                outerLineCount={34}
                warpIntensity={0.9}
                rotation={-45}
                edgeFadeWidth={0.0}
                colorCycleSpeed={1.0}
                brightness={0.15}
                opacity={0.8}
                color1="#ffffff"
                color2="#ffffff"
                color3="#ffffff"
                enableMouseInteraction={true}
                mouseInfluence={2.0}
              />
            </div>
            <motion.button
              onClick={handleEnter}
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              className="bg-white text-black font-bold tracking-[0.3em] text-sm uppercase rounded-full py-4 px-12 relative z-10 shadow-[0_0_30px_rgba(255,255,255,0.4)] hover:shadow-[0_0_50px_rgba(255,255,255,0.7)] transition-shadow duration-500"
            >
              <DecryptedText
                text="ENTER"
                speed={50}
                maxIterations={15}
                characters="01!*?"
                animateOn="hover"
                encryptedClassName="text-neutral-500"
              />
            </motion.button>
          </motion.div>
        )}

        {state === "gatekeeper" && (
          <motion.div
            key="gatekeeper"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 1, ease: "easeOut", delay: 0.5 }}
            className="w-full h-full absolute inset-0 flex items-center justify-center"
          >
            <div className="absolute inset-0 z-0 pointer-events-auto">
              <DotField 
                dotRadius={1.5}
                dotSpacing={16}
                cursorRadius={600}
                cursorForce={0.2}
                bulgeOnly={true}
                bulgeStrength={80}
                glowRadius={250}
                sparkle={true}
                waveAmplitude={1.5}
                gradientFrom="rgba(255, 255, 255, 0.4)"
                gradientTo="rgba(255, 255, 255, 0.1)"
                glowColor="rgba(255, 255, 255, 0.05)"
              />
            </div>
            
            <div className="flex flex-col items-center justify-center text-center max-w-2xl px-8 py-10 mx-6 w-full relative z-10 bg-black/60 backdrop-blur-2xl border border-white/10 rounded-[2rem] shadow-[inset_0_0_30px_rgba(255,255,255,0.02),0_20px_50px_rgba(0,0,0,0.5)]">
              <h1 className="tracking-[0.4em] text-2xl md:text-4xl font-bold mb-6 uppercase text-white drop-shadow-[0_0_15px_rgba(255,255,255,0.8)]">
                <DecryptedText
                  text="WARNING"
                  speed={70}
                  maxIterations={20}
                  characters="01!@#$%^&*?"
                  animateOn="view"
                  encryptedClassName="text-neutral-500"
                />
              </h1>

              <div className="space-y-4 text-neutral-300 text-sm md:text-base leading-relaxed mb-8 font-light">
                <p>
                  This is not your average 30-day shred. <strong className="text-red-500 drop-shadow-[0_0_15px_rgba(220,38,38,1)]">None of this content is generated by AI.</strong>
                </p>
                <p>
                  Every training program, nutrition protocol, and progression model in Project Ultimatum is written entirely from real-world experience, elite coaching data, and peer-reviewed sports science.
                </p>
                <p>
                  This is a zero-bullshit, evidence-based system engineered exclusively for natural lifters—with all citations and references transparently available inside the website.
                </p>
              </div>

              <div className="flex flex-col md:flex-row gap-4 justify-center items-center w-full mt-4">
                <motion.button
                  onClick={() => setState("protocol")}
                  initial={{ 
                    backgroundColor: "#ffffff", 
                    color: "#000000", 
                    borderColor: "#ffffff" 
                  }}
                  whileHover={{ 
                    backgroundColor: "#000000", 
                    color: "#ffffff",
                    borderColor: "#ffffff",
                    scale: 1.05
                  }}
                  whileTap={{ scale: 0.95 }}
                  transition={{ duration: 0.4, ease: "easeInOut" }}
                  className="w-full md:w-auto font-bold tracking-[0.2em] uppercase py-3 px-8 text-xs md:text-sm rounded-full shadow-[0_0_20px_rgba(255,255,255,0.3)] hover:shadow-[0_0_40px_rgba(255,255,255,0.6)] transition-shadow border-2"
                >
                  NEW USER - INITIALIZE
                </motion.button>

                <motion.button
                  onClick={() => router.push("/auth")}
                  initial={{ 
                    backgroundColor: "transparent", 
                    color: "#ffffff", 
                    borderColor: "rgba(255,255,255,0.3)" 
                  }}
                  whileHover={{ 
                    backgroundColor: "rgba(255,255,255,0.1)", 
                    color: "#ffffff",
                    borderColor: "#ffffff",
                    scale: 1.05
                  }}
                  whileTap={{ scale: 0.95 }}
                  transition={{ duration: 0.4, ease: "easeInOut" }}
                  className="w-full md:w-auto font-bold tracking-[0.2em] uppercase py-3 px-8 text-xs md:text-sm rounded-full transition-shadow border-2"
                >
                  RETURNING USER - LOGIN
                </motion.button>
              </div>
            </div>
          </motion.div>
        )}

        {state === "protocol" && (
          <motion.div
            key="protocol"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 1.5, ease: "easeInOut" }}
            className="w-full bg-black min-h-screen text-white"
          >
            {/* The Sticky Scroll Section */}
            <TruthsSection />

            {/* End of Sequence / Call to Action */}
            <div className="h-screen bg-black flex flex-col items-center justify-center relative">
              <div className="absolute inset-0 bg-gradient-to-t from-neutral-900/10 to-black z-0 pointer-events-none"></div>
              
              <div className="relative z-10 flex flex-col items-center text-center px-6">
                <motion.button
                  whileHover={{ 
                    scale: 1.05, 
                    backgroundColor: "#000000",
                    color: "#ffffff",
                    borderColor: "#ffffff"
                  }}
                  whileTap={{ scale: 0.95 }}
                  className="px-10 py-6 bg-white text-black font-bold uppercase tracking-[0.2em] text-sm md:text-base rounded-full shadow-[0_0_30px_rgba(255,255,255,0.1)] hover:shadow-[0_0_50px_rgba(255,255,255,0.4)] border-2 border-transparent transition-colors duration-300"
                  onClick={() => router.push("/directive")}
                >
                  Continue for Personalization
                </motion.button>
              </div>
            </div>
          </motion.div>
        )}

      </AnimatePresence>
    </main>
  );
}
